orbs:
  pypi: pennlabs/pypi-tools@0.0.3
version: 2.1
jobs:
  unit_test:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Unit test
          command: |
            pip install tox
            pip install codecov
            tox
            codecov -t $TOKEN_CODECOV
  publish_prod:
    environment:
      IMAGE_NAME: mbouamama/myjwt/myjwt
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image prod
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              DOCKER_TAG="latest"
            fi

            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            fi
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.pkg.github.com
            docker build -t $IMAGE_NAME:$DOCKER_TAG .
            docker push $IMAGE_NAME:$DOCKER_TAG
workflows:
  deploy:
    jobs:
      - unit_test:
          context: myjwt
          filters:
            tags:
              only: /.*/
      - pypi/publish:
          context: myjwt
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/[0-9]+(\.[0-9]+)*/'
          requires:
            - unit_test
      - publish_prod:
          context: api_proxy
          filters:
            branches:
              only: master
            tags:
              only: /.*/